### ISSUE TITLE
Flow Runs Filter 422

### ISSUE THREAD

**Issue by stackoverfloweth** [PrefectHQ/prefect-ui-library#663] opened 2022-10-07 21:04 UTC
issue is likely coming from `useRouterQueryParam` in vue-compositions.

if you update your filter, see the change in the url, use the browser to go back, then use the browser to go forward, you'll get several 422 errors.

the request gets malformed where `flows` (not exclusive to flows) goes from `any_` array to `any_` string

before
```json
{
    "flows": {
        "id": {
            "any_": [
                "171b69f8-0978-4da8-aeda-9cf36678a307"
            ]
        }
    },
    "flow_runs": {
        "expected_start_time": {
            "after_": "2022-09-30T05:00:00.000Z",
            "before_": "2022-10-09T04:59:59.000Z"
        }
    },
    "sort": "EXPECTED_START_TIME_DESC"
}
```

after 
```json
{
  "flows": {
    "id": {
      "any_": "171b69f8-0978-4da8-aeda-9cf36678a307"
    }
  },
  "flow_runs": {
    "expected_start_time": {
      "after_": "2022-09-30T05:00:00.000Z",
      "before_": "2022-10-09T04:59:59.000Z"
    }
  },
  "sort": "EXPECTED_START_TIME_DESC"
}
```

**Comment by pleek91** [comment] 2023-02-28 23:14
Unable to reproduce. Most likely fixed by https://github.com/PrefectHQ/prefect-ui-library/pull/1067

**Closed by pleek91** 2023-02-28 23:14 UTC
Labels: priority:low
