### ISSUE TITLE
Blocks catalog shows white background for logos in dark mode

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect-ui-library#1158] opened 2023-02-16 01:03 UTC
Blocks logos have a transparent background, but when displayed in the dark mode of blocks catalog on staging, it shows a white background
![image](https://user-images.githubusercontent.com/15331990/219231136-1a6c8a13-e7d8-4a8a-8e8d-99d05be898ef.png)

**Comment by ahuang11** [comment] 2023-02-16 01:05
Updating the CSS of `class="logo-image logo-image--size-md block-type-card-preview__logo"` to `background_color: "transparent"` works:

![image](https://user-images.githubusercontent.com/15331990/219231729-1d4cbed6-6bff-4eaf-9396-e20e3fb18677.png)

**Comment by pleek91** [comment] 2023-02-23 16:21
This is intentional. We don't control logos and some (like the database credentials) have very low contrast on a dark background. Having a consistent light colored background when displaying logos gives better consistency of color contrast. 

Closing as this is working as intended.

**Closed by pleek91** 2023-02-23 16:21 UTC

**Comment by ahuang11** [comment] 2023-02-23 17:35
Can we have it like blocks catalog? https://docs.prefect.io/collections/catalog/
